FROM python:3.10

RUN apt-get update

RUN mkdir /home/service
WORKDIR /home/service

ADD ./poetry.lock /home/service
ADD ./pyproject.toml /home/service
ADD ./final_pipeline /home/service/final_pipeline
ADD ./service /home/service/service
ADD ./Makefile /home/service

ENV PROMETHEUS_MULTIPROC_DIR=/metrics
RUN mkdir -p /metrics

ARG POETRY_HOME=/opt/poetry
ENV PATH=${POETRY_HOME}/bin:${PATH}
RUN curl -sSL https://install.python-poetry.org | python3 -
RUN make install_dependencies
