FROM python:3.10

RUN apt-get update
#RUN apt-get install -y python3.10 python3-pip

RUN mkdir /home/service
WORKDIR /home/service

ADD ./poetry.lock /home/service
ADD ./pyproject.toml /home/service
ADD ./final_pipeline /home/service/final_pipeline
ADD ./service /home/service/service
ADD ./Makefile /home/service

ARG POETRY_HOME=/opt/poetry
ENV PATH=${POETRY_HOME}/bin:${PATH}
RUN curl -sSL https://install.python-poetry.org | python3 -
RUN make install_dependencies

CMD ["poetry", "run", "uvicorn", "service.main:app", "--host", "0.0.0.0" ]